//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CHernandezCargarMasivaEntities : DbContext
    {
        public CHernandezCargarMasivaEntities()
            : base("name=CHernandezCargarMasivaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Cargo> Cargoes { get; set; }
    
        public virtual int CargaMasivaCSV(string id, Nullable<decimal> amount, string status, Nullable<System.DateTime> update_At, string company_Id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("Amount", amount) :
                new ObjectParameter("Amount", typeof(decimal));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var update_AtParameter = update_At.HasValue ?
                new ObjectParameter("Update_At", update_At) :
                new ObjectParameter("Update_At", typeof(System.DateTime));
    
            var company_IdParameter = company_Id != null ?
                new ObjectParameter("Company_Id", company_Id) :
                new ObjectParameter("Company_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CargaMasivaCSV", idParameter, amountParameter, statusParameter, update_AtParameter, company_IdParameter);
        }
    }
}
